# Required by readthedocs
version: 2

# Set the OS, Python version etc.
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Declare Python requirements
python:
  install:
    - requirements: requirements.txt

# Build documentation using the configuration file below
sphinx:
  configuration: docs/source/conf.py