# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
project = "Rosetta"
copyright = "2023, Kéita A. Yokoyama"
author = "Kéita A. Yokoyama"

# The full version, including alpha/beta/rc tags
release = "0.0.1"

# The language for content autogenerated by Sphinx.
language = "en"

# -- General configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings.
extensions = [
    "myst_parser",  # convert Markdown (MyST) to RST
    "sphinxcontrib.bibtex",  # parse and render BibTeX
    "sphinx.ext.autodoc",  # automatically generate docs from code comments
    "sphinx.ext.napoleon",  # convert Google/NumPy-style docstrings to RST
    "sphinx_design",  # add more modern UI features
    "sphinx_copybutton",  # add copy button to code blocks
    "sphinx_favicon",  # customize favicons
    "sphinxext.opengraph",  # add Open Graph metadata
    "sphinxcontrib.matlab",  # process Matlab code comments with Sphinx
]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Multi-programming language support --------------------------------------
# Do not set a primary domain when Sphinx interprets raw code. This forces
# users to explicitly specify what language is being written.
primary_domain = None

# -- HTML output -------------------------------------------------------------
html_static_path = ["_static"]
html_title = "Rosetta Documentation"
html_theme = "furo"
html_theme_options = {
    "light_logo": "brand/rosetta-logo-dark.svg",
    "dark_logo": "brand/rosetta-logo-light.svg",
    "light_css_variables": {
        "color-brand-primary": "#13294B", # based on UNC's Navy
        "color-brand-content": "#13294B",
    },
    "dark_css_variables": {
        "color-brand-primary": "#4B9CD3", # based on UNC's Carolina Blue
        "color-brand-content": "#4B9CD3",
    },
    "sidebar_hide_name": True,
    "announcement": None,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/rosetta-code/",
            "html": """<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>""",
            "class": "",
        },
    ],
    "source_repository": "https://github.com/rosetta-code/rosetta-doc/",
    "source_branch": "main",
    "source_directory": "docs/source/",
}
favicons = [
    {
        "rel": "icon",
        "href": "brand/rosetta-favicon.png"
    },
    {
        "rel": "apple-touch-icon",
        "href": "brand/rosetta-favicon.png",
    },
]

# -- Modifying HTML for landing (front) page ---------------------------------
templates_path = ["_template"]
html_additional_pages = {'index': 'home.html'}

# -- MyST: enable additional features ----------------------------------------
myst_enable_extensions = [
    "colon_fence",  # let directives be written to play nice w/ standard MD
    "attrs_block",  # let MyST parse some block attributes before content
    "attrs_inline",  # let MYST parse some attributes after content, inline
    "deflist",  # let mouse hovers preview glossary entries for key terms
]
myst_heading_anchors = 3  # create HTML tags for up to 3 heading levels

# -- BibTex: configure where citations live and how they should be rendered --
bibtex_bibfiles = ['cite.bib']
bibtex_default_style = "unsrt"
bibtex_reference_style = "author_year"